# @package _global_

defaults:
  - _self_
  - callbacks:
    - default
  - paths: default
  - hydra: default

# 实验配置
experiment_path: logs/proteinStability_fusion_diff
name: "proteinStability_fusion_diff"

# parameters for training
train:
  train: True
  test: True
  debug: false
  force_restart: True
  ckpt_path: last.ckpt
  seed: 45
  lr: 0.01
  monitor: val/rho_avg_spearman
  mode:  max
  patience: 20

# other settings
print_config: True
ignore_warnings: True
seed: 42

# task configuration
task:
  _target_: stability/megascale
  model: ${model}
  criterion:
    _target_: tristab.modules.mseloss.MSELoss
  optimizer:
    type: adamw
    _partial_: true
    lr: 0.0001
    betas: [0.9, 0.98]
    weight_decay: 0.01
  lr_scheduler:
    type: plateau
    lr: 0.001
    factor: 0.2
    mode: min
    monitor: val/rho_avg_rmse

# model configuration
model:
  _target_: esmfusion
  esm_name: 'esm2_t33_650M_UR50D'
  mpnn_name: 'ProteinMPNN'
  esm_tune: False
  mpnn_tune: True
  encoder_mpnn:
    d_model: 128
    n_enc_layers: 3
    n_dec_layers: 3
    tune: false
    use_input_decoding_order: True
  mlp:
    input_dim: 1792
    hidden_dim: 1024
    num_layers: 2
    output_dim: 21
    dropout: 0.2
  dropout: 0.2

# data module configuration
datamodule:
  _target_: megascale
  batch_size: 1
  num_workers: 8
  pin_memory: true
  alphabet:
    name: esm
    featurizer: megascale
  
  
trainer:
  _target_: pytorch_lightning.Trainer
  gpus: [2]
  min_epochs: 1
  max_epochs: 200
  enable_progress_bar: true
  log_every_n_steps: 10
  resume_from_checkpoint: null
  strategy: null
  precision: 16
  gradient_clip_val: 0.0
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  reload_dataloaders_every_n_epochs: 100000
  replace_sampler_ddp: false
  max_steps: 200000
